name: Promote release

on:
    workflow_call:
        inputs:
            selectedVersion:
                type: string
            payloadLibrary:
                type: string
            selectedRepository:
                type: string
            forceRc:
                type: boolean
            dir:
                type: string
            allRepositoriesJson:
                type: string
            org:
                type: string

jobs:
    check:
        name: Select repositories to promote
        runs-on: ubuntu-latest
        outputs:
            latest-version: ${{ steps.version.outputs.tag }}
            matrix: ${{ steps.setVariables.outputs.matrix }}

        steps:
            -   uses: actions/checkout@v3

            -   name: Get latest version from package.json
                id: version
                run: cd ${{ inputs.dir }} && echo "tag=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)" >> $GITHUB_OUTPUT
                shell: bash

            -   id: setVariables
                run: echo "matrix=${{ inputs.allRepositoriesJson }}" >> $GITHUB_OUTPUT
                shell: bash

    promote-all:
        name: Promote all repositories
        needs: check
        if: inputs.selectedRepository == 'all'
        runs-on: ubuntu-latest

        strategy:
            matrix:
                repository: ["action-test-2", "action-test-3"]
#                repository: ${{fromJson(needs.check.outputs.matrix)}}

        steps:
            -   name: bla bla ${{fromJson(needs.check.outputs.matrix)}}
                run: echo ""
#            -   name: Promote version ${{ inputs.selectedVersion || needs.check.outputs.latest-version }} to ${{ inputs.org }}/${{ matrix.repository }} repository. Force RC is ${{ inputs.forceRc }}
#                uses: passeidireto/trigger-external-workflow-action@main
#                env:
#                    PAYLOAD_VERSION: ${{ inputs.selectedVersion || needs.check.outputs.latest-version }}
#                    PAYLOAD_LIBRARY: ${{ inputs.payloadLibrary }}
#                    PAYLOAD_FORCERC: ${{ inputs.forceRc }}
#                with:
#                    repository: ${{ inputs.org }}/${{ matrix.repository }}
#                    event: promote
#                    github_pat: ${{ secrets.AUTH_TOKEN }}

    promote-one:
        name: Promote selected repository
        needs: check
        if: inputs.selectedRepository != 'all'
        runs-on: ubuntu-latest

        steps:
            -   name: Promote version ${{ inputs.selectedVersion || needs.check.outputs.latest-version }} to ${{ inputs.org }}/${{ inputs.selectedRepository }} repository. Force RC is ${{ inputs.forceRc }}
                uses: passeidireto/trigger-external-workflow-action@main
                env:
                    PAYLOAD_VERSION: ${{ inputs.selectedVersion || needs.check.outputs.latest-version }}
                    PAYLOAD_LIBRARY: ${{ inputs.payloadLibrary }}
                    PAYLOAD_FORCERC: ${{ inputs.forceRc }}
                with:
                    repository: ${{ inputs.org }}/${{ inputs.selectedRepository }}
                    event: promote
                    github_pat: ${{ secrets.AUTH_TOKEN }}
