name: Promote release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Define version or last'
            repository:
                description: 'Promoted repository'
                required: true
                default: 'all'
                type: choice
                options:
                    - all
                    - action-test-2
                    - action-test-3
            forceRc:
                description: 'Force RC version bump'
                required: true
                type: boolean

jobs:
    promote-release:
        uses: ./.github/workflows/promote-release-reuse.yml
        with:
            selectedVersion: ${{ inputs.version }}
            payloadLibrary: "action-test-1"
            selectedRepository: ${{ inputs.repository }}
            forceRc: ${{ inputs.forceRc }}
            dir: .
            allRepositoriesJson: '["action-test-2", "action-test-3"]'
            org: "giedriusvickus"
        secrets: inherit
