name: Trigger build with workflow

on:
    workflow_dispatch:
        inputs:
            sha:
                description: 'Define git sha'

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest

        permissions:
            contents: write
            packages: write

        steps:
            -   name: Trigger build
                uses: passeidireto/trigger-external-workflow-action@main
                env:
                    PAYLOAD_COMMIT_MSG: Automated commit bim bam
                    PAYLOAD_COMMIT_SHA: ${{ inputs.sha }}
                with:
                    repository: giedriusvickus/action-test-1
                    event: automated-deploy
                    github_pat: ${{ secrets.AUTH_TOKEN }}
